/**
 * Server entry point.
 * - Loads from .env
 * - Sets up express
 * - Mounts authentication routes
 * - Connects to MongoDB using Mongoose
 * - Starts the Express server on port 5000
 * NOTE: The initial version of this code was originally generated by AI, given this JSDoc as a prompt. 
 * It was then reviewed, edited, and refined.
 */
import dotenv from 'dotenv';
dotenv.config(); 

import express, { json } from 'express';
const app = express();
import authRouter from './auth.js';

app.use(json());
app.use('/api', authRouter); 

import { connect } from 'mongoose';

/**
 * Connect to MongoDB using the URI from environment variables.
 * Logs success or error messages to the console.
 */
connect(process.env.MONGO_DB_URI)
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.error('MongoDB connection error:', err));

/**
 * Start the Express server on port 5000.
 * Logs a message when the server is running.
 */
app.listen(5000, () => console.log('Express server running on port 5000'));